export const CREATURES = {
  GET_LIST: "CREATURES/GET_LIST",
  GET_LIST_SUCCESS: "CREATURES/GET_LIST_SUCCESS",
  GET_LIST_FAIL: "CREATURES/GET_LIST_FAIL",
  GET_BY_ID: "CREATURES/GET_BY_ID",
  GET_BY_ID_SUCCESS: "CREATURES/GET_BY_ID_SUCCESS",

  GET_LIST_CREATURE_REDBOOK_STATISTIC_SUCCESS: 'CREATURES/GET_LIST_CREATURE_REDBOOK_STATISTIC_SUCCESS',
  GET_LIST_CREATURE_REDBOOK_STATISTIC: 'CREATURES/GET_LIST_CREATURE_REDBOOK_STATISTIC',
  CHANGE_PAGE: "CREATURES/CHANGE_PAGE",
  SET_LOADING: "CREATURES/SET_LOADING",

  SET_CREATURE_DETAIL: 'CREATURES/SET_CREATURE_DETAIL'
};
