export const CREATURES = {
  GET_LIST: "CREATURES/GET_LIST",
  GET_LIST_SUCCESS: "CREATURES/GET_LIST_SUCCESS",
  GET_LIST_FAIL: "CREATURES/GET_LIST_FAIL",

  GET_LIST_CREATURE_REDBOOK_STATISTIC_SUCCESS: 'CREATURES/GET_LIST_CREATURE_REDBOOK_STATISTIC_SUCCESS',
  GET_LIST_CREATURE_REDBOOK_STATISTIC: 'CREATURES/GET_LIST_CREATURE_REDBOOK_STATISTIC',

};
