export const CLASSIFY = {
  GET_LIST: "CLASSIFY/GET_LIST",
  GET_LIST_SUCCESS: "CLASSIFY/GET_LIST_SUCCESS",
  GET_LIST_FAIL: "CLASSIFY/GET_LIST_FAIL",
  
  CHANGE_TAB: "CLASSIFY/CHANGE_TAB",
  TOGGLE_FILTER: 'CLASSIFY/TOGGLE_FILTER',

  SYNC_TO_EDIT: 'CLASSIFY/SYNC_TO_EDIT',
  SYNC_FROM_EDIT: 'CLASSIFY/SYNC_FROM_EDIT',

  FILTER_CHANGE_KEY_WORD: 'CLASSIFY/FILTER_CHANGE_KEY_WORD',
  FILTER_CHANGE_CLASSIFY: 'CLASSIFY/FILTER_CHANGE_CLASSIFY',
  FILTER_CHANGE_REDBOOK_CONDITION: 'CLASSIFY/FILTER_CHANGE_REDBOOK_CONDITION',
  FILTER_REMOVE: 'CLASSIFY/FILTER_REMOVE'
};
